name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Build fat JAR
      run: ./gradlew fatJar

    - name: Test JAR generation
      run: |
        echo "Testing TLA+-Smith JAR..."
        java -jar build/libs/tlaplus-smith-1.0.0-all.jar 1 42
        echo "JAR test completed successfully!"

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: tlaplus-smith-jar
        path: build/libs/tlaplus-smith-1.0.0-all.jar